### ISSUE TITLE
elasticsearch container won't start

### ISSUE THREAD

**Issue by willkg** [mozilla-services/buildhub2#532]
When going through the developer documentation, running `make build` seems to work fine, but then running `make run` fails.

The `web` container depends on the `elasticsearch` container starting, but it dies at startup with this line:

```
elasticsearch    | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```

This issue covers looking into that and fixing it.

**Comment by willkg** [comment]
It was just a problem with my machine. No biggie.

https://www.elastic.co/guide/en/elasticsearch/reference/6.7/docker.html#docker-cli-run-prod-mode

**Comment by peterbe** [comment]
You're sorta opening a can of worms here. ES is a beast and I found, when I tried to populate my local ES instance **inside** Docker, that it could never handle it. I *could* have super-upp'ed the Docker-for-mac configuration but I didn't want to. So, instead I made my Django inside Docker talk to an Elasticsearch here on my host. That worked but cumbersome. I.e. I opened two terminals. In one `docker-compose run this and that` and in another terminal `cd elasticsearch-6.x.x && ./bin/elasticsearch`.

The problems arose from trying to index EVERYTHING from the old Kinto days. That was 10-30x larger because historically we used to save every single locale. 

Not entirely sure this is the right place to drop this comment but I'd like to share the story since it might help others.
