### ISSUE TITLE
onboarding-related issues

### ISSUE THREAD

**Issue by willkg** [mozilla-services/buildhub2#533]
I'm coming up to speed on Buildhub2 and instead of creating a bunch of issues, I'm going to create this one and hang most things related to updating docs, fixing environment issues, and such as I get a local dev environment working off it.

**Comment by willkg** [comment]
The dev docs here:

https://buildhub2.readthedocs.io/en/latest/bootstrapping.html#starting-from-scratch

say this:

```
First create the PostgreSQL database:

$ ./manage.py migrate

That will create all the necessary tables.

Next, you need to create the Elasticsearch index:

$ ./manage.py reindex-elasticsearch

Check that this created the index by visiting http://localhost:9200/buildhub2 where the 
base URL needs to match what you set DJANGO_ES_URLS to.
```

That doesn't work. I think you can do `make migrate`, but that raises an error that `/usr/bin/git` isn't in the container:

```
...
 File "/usr/local/lib/python3.7/site-packages/configurations/utils.py", line 18, in <genexpr>
    for name in filter(isuppercase, dir(obj)))
  File "/app/buildhub/settings.py", line 362, in VERSION
    ["/usr/bin/git", "describe", "--tags", "--always", "--abbrev=0"]
  File "/usr/local/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/git': '/usr/bin/git'
make: *** [Makefile:40: migrate] Error 1
```

Probably need to install git in the container and update the docs to `make migrate`. Though I might follow what I did with Socorro and have a `make setup` that covers a bunch of bootstrapping tasks.

**Comment by jwhitlock** [comment]
It appears the code is trying to return an empty dict ``{}`` on failure - should the exception handling be extended rather than install git?

**Comment by willkg** [comment]
I'm looking at that. What other things expect git? Why did this work before--was there a previous image that had git installed? Should we be generating a basic `version.json`?

Socorro does it differently. I think I might pull that code over.

**Comment by peterbe** [comment]
I think I've mentioned this before, somewhere, but it's worth mentioning again. 
I created almost all the code for buildhub2 in June 2018 in about two weeks. In the beginning I used docker-compose for everything and made the circleCI config be very close to local dev with docker-compose for the benefit of shipping docker builds to Dockerhub. Once I got all that working, I started doing dev differently. I set up a Procfile and use honcho start Elasticsearch, the daemon, and the Django runserver that way and I used the already installed Postgres on my macOS host. This made it easier and much faster to hack on things but at the cost of the dev environment being less useful since I wasn't using it. Kinda. 

Point is; that might many times explain how the hell I managed to get anything done even though there are so many (as you point out) flaws in the local dev version. 

Not an excuse. More like an explanation.

**Comment by willkg** [comment]
@peterbe I totally get it. I'm hitting issues because I've got a different set up (OSX vs. Linux) and the first person to onboard. I wouldn't expect anything different from any project.

I think you did a phenomenal job with this project! You should feel good about what you did here!

**Comment by willkg** [comment]
I think the changes I'm going to make under this umbrella are done now. Closing it out.
